# Generated by Django 5.1.3 on 2024-12-08 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_post_post_image_post_tags_alter_post_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="comment_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
