# Generated by Django 5.1.3 on 2025-01-09 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_add_category_to_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
