# Generated by Django 4.2 on 2025-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
