# Generated by Django 4.2 on 2025-01-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_post_content_post_articles_post_subheadings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="articles",
        ),
        migrations.RemoveField(
            model_name="post",
            name="subheadings",
        ),
    ]
