# Generated by Django 4.2 on 2025-01-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_remove_post_articles_remove_post_subheadings"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
