# Generated by Django 4.2 on 2025-01-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_post_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="untitled", max_length=250),
            preserve_default=False,
        ),
    ]
