# Generated by Django 4.2 on 2025-01-18 16:57

from django.db import migrations
from django.utils.text import slugify

def update_slugs(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in Post.objects.all():
        if post.slug == 'untitled':  # Match the default you set
            post.slug = slugify(post.title)
            original_slug = post.slug
            count = 1
            while Post.objects.filter(slug=post.slug).exists():
                post.slug = f"{original_slug}-{count}"
                count += 1
            post.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_slug'),  # Replace with your latest migration
    ]

    operations = [
        migrations.RunPython(update_slugs),
    ]
